### ISSUE TITLE
ArmPkg/ArmGic: invalid register offset written when on GICv3

### ISSUE THREAD

**Issue by lersek** [tianocore/edk2#108]
Please see
https://bugzilla.redhat.com/show_bug.cgi?id=1356655
for the details.

@ardbiesheuvel, @leiflindholm, could you guys please take a look if you have the time? Thank you!

**Comment by ardbiesheuvel** [comment]
Is this with or without

28f8d28faabf ArmPkg/ArmGicLib: manage GICv3 SPI state at the distributor

applied?

**Comment by lersek** [comment]
That commit is 7 days old, we don't have it (yet) in our latest downstream rebase. I'll give it a whirl (hopefully soon). Thank you for the tip!

@rhdrjones: ^^^

**Comment by lersek** [comment]
@ardbiesheuvel thank you very much, commit 28f8d28 fixes the problem for us!
