### ISSUE TITLE
Build Failed on Linux

### ISSUE THREAD

**Issue by chaostheory88** [tianocore/edk2#11]
While I was trying to build against the last git repo version I've encountered the following error:
edk2/MdePkg/Library/UefiDevicePathLib/DevicePathFromText.c:2796:12: error: pointer targets in assignment differ in signedness [-Werror=pointer-sign]
   AsciiStr = WiFiDp->SSId;

Cheers.

**Comment by chaostheory88** [comment]
I guess I've solved changing the type of WIFI_DEVICE_PATH->SSId[32] from UINT8 to CHAR8.
Cheers.

**Comment by logintxt** [comment]
Great. I solved it via an iSCSI driver connected to a logtxt, anyway.

**Comment by lersek** [comment]
This item should be closed. I would, if I could.
