### ISSUE TITLE
Failed to start command .\SecMain on Ubuntu

### ISSUE THREAD

**Issue by mingloo** [tianocore/edk2#15]
Hi all,

When I trying to use `build run` command to run the UEFI emulator, I've got the following failed information:
![image](https://cloud.githubusercontent.com/assets/1622929/8223596/95c13ca0-15ac-11e5-987f-48a9e02235df.png)

However, if I run the `./EmulatorPkg/build.sh run`, the GOP Window will be started as follows:
![image](https://cloud.githubusercontent.com/assets/1622929/8223587/5966f7ea-15ac-11e5-93b2-ce26edb6b855.png)

Any difference between these two command? And why the `build run` command will failed?

**Comment by jljusten** [comment]
@mingloo: 'build run' was developed in a very hacky way just to support the NT32 platform. Maybe it could be made more general.

For both EmulatorPkg, OvmfPkg and DuetPkg, we use a build.sh script that helps to build and run the platform, and we don't bother with 'build run'.

**Comment by lersek** [comment]
Closing as per previous commit.
