### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by VladislavVesely** [tianocore/edk2#20]
error 4000: Instance of library class [TpmMeasurementLibNull] is not found
	in [~/Documents/Vyvoj/Hackintosh/MdeModulePkg/Universal/Variable/RuntimeDxe/VariableRuntimeDxe.inf] [X64]
	consumed by module [~/Documents/Vyvoj/Hackintosh/MdeModulePkg/Universal/Variable/RuntimeDxe/VariableRuntimeDxe.inf]

**Comment by lersek** [comment]
Stale item. Should be closed.

**Comment by jljusten** [comment]
@VladislavVesely: let us know if you are still having trouble building.

And, maybe note which platform.

Thanks!
