### ISSUE TITLE
EDK Shell Locking Up after a few minutes

### ISSUE THREAD

**Issue by CMCDragonkai** [tianocore/edk2#35]
I just tried the UEFI shell application: https://github.com/tianocore/edk2/tree/master/EdkShellBinPkg/FullShell/X64

Loaded it into a USB drive, with UEFI version 2.31 American Megatrends 4.655.

Using gummiboot 48, I launched the shell, and everything was working for a few minutes.

Eventually the keyboard locks up, and nothing can be done.

This never happens when I go into the Linux OS, it is fully stable. This is a brand new laptop.

**Comment by lersek** [comment]
Changed title based on previous comment -- it makes clear that this is not about the "new" UEFI shell.
