### ISSUE TITLE
win7 64bit install failed

### ISSUE THREAD

**Issue by maqiangddb** [tianocore/edk2#38]
If this package: edk2.git-ovmf-x64-0-20151216.b1379.g23df19a.noarch support win7 efi install? I tried but failed.

**Comment by lersek** [comment]
UEFI Win7 installation should work with OVMF, yes.

Given how many users have working UEFI Windows 7 installations on top of OVMF, this looks like an environment or setup problem. I suggest that if your problem persists, please post about it to edk2-devel.

@jljusten I suggest we close this for now; there are no technical details in the report, plus see the above. Thanks.

**Comment by lersek** [comment]
To quote Bugzilla: INSUFFICIENT_DATA; closing.
