### ISSUE TITLE
I NEED HELP! I CAN NOT BUILD 202211 EDK2

### ISSUE THREAD

**Issue by fisheggM** [tianocore/edk2#4055]
this is the log in the terminal when i execute "edksetup forcerebuild Vs2019"

 Workspace is not changed.
          PATH      = C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\Bin\Win32;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Common7\IDE\VC\VCPackages;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\MSBuild\Current\bin\Roslyn;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Team Tools\Performance Tools\x64;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\HTML Help Workshop;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Common7\Tools\devinit;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\\MSBuild\Current\Bin;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Common7\IDE\;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Common7\Tools\;C:\Program Files\Eclipse Foundation\jdk-8.0.302.8-hotspot\bin;C:\WINDOWS\System32\OpenSSH\;C:\WINDOWS\System32\Wbem;E:\mongoserver\bin;C:\Users\Administrator\AppData\Roaming\python3;E:\PythonMap\Python_v3.11.1\;E:\PythonMap\Python_v3.11.1\\Scripts\;C:\Users\Administrator\AppData\Roaming\python2\appdata\Lib\site-packages;C:\Users\Administrator\AppData\Roaming\python3\Scripts;C:\ProgramData\chocolatey\bin;C:\Program Files\NASM;C:\Program Files\qemu;C:\Users\a\Desktop\mingw64\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\NASM;C:\IASL;C:\Windows\System32;C:\WINDOWS\system32;SystemRoot%\system32;C:\WINDOWS;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\IncrediBuild;C:\Program Files\Git\cmd;E:\crgwin;C:\Users\a\scoop\shims;C:\Users\a\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\JetBrains\CLion 2022.3.1\bin;;C:\Program Files\JetBrains\IntelliJ IDEA 2022.3.1\bin;;C:\Program Files\JetBrains\PyCharm 2022.3.1\bin;;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\VC\Tools\Llvm\x64\bin;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe

     WORKSPACE      = C:\FishLoader
EDK_TOOLS_PATH      = C:\FishLoader\BaseTools
BASE_TOOLS_PATH     = C:\FishLoader\BaseTools
 EDK_TOOLS_BIN      = C:\FishLoader\BaseTools\Bin\Win32
     CONF_PATH      = C:\FishLoader\Conf

Using Pip Basetools
               PATH = C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\BinPipWrappers\WindowsLike;C:\FishLoader\BaseTools\Bin\Win32;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Common7\IDE\VC\VCPackages;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\MSBuild\Current\bin\Roslyn;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Team Tools\Performance Tools\x64;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\HTML Help Workshop;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Common7\Tools\devinit;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\\MSBuild\Current\Bin;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Common7\IDE\;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Common7\Tools\;C:\Program Files\Eclipse Foundation\jdk-8.0.302.8-hotspot\bin;C:\WINDOWS\System32\OpenSSH\;C:\WINDOWS\System32\Wbem;E:\mongoserver\bin;C:\Users\Administrator\AppData\Roaming\python3;E:\PythonMap\Python_v3.11.1\;E:\PythonMap\Python_v3.11.1\\Scripts\;C:\Users\Administrator\AppData\Roaming\python2\appdata\Lib\site-packages;C:\Users\Administrator\AppData\Roaming\python3\Scripts;C:\ProgramData\chocolatey\bin;C:\Program Files\NASM;C:\Program Files\qemu;C:\Users\a\Desktop\mingw64\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\NASM;C:\IASL;C:\Windows\System32;C:\WINDOWS\system32;SystemRoot%\system32;C:\WINDOWS;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\IncrediBuild;C:\Program Files\Git\cmd;E:\crgwin;C:\Users\a\scoop\shims;C:\Users\a\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\JetBrains\CLion 2022.3.1\bin;;C:\Program Files\JetBrains\IntelliJ IDEA 2022.3.1\bin;;C:\Program Files\JetBrains\PyCharm 2022.3.1\bin;;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\VC\Tools\Llvm\x64\bin;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;E:\Visual Studio 2022\Visual Studio IDE\2019\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe
         PYTHONPATH =

Microsoft (R) Program Maintenance Utility Version 14.29.30148.0
Copyright (C) Microsoft Corporation.  All rights reserved.

execute command "nmake cleanall" in directory C:\FishLoader\BaseTools\Source\Python

Microsoft (R) Program Maintenance Utility Version 14.29.30148.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Could Not Find C:\FishLoader\BaseTools\Source\Python\*.pyc

C:\FishLoader\BaseTools\Source\C\Makefiles\NmakeSubdirs.py:135: DeprecationWarning: currentThread() is deprecated, use current_thread() instead
  self.running.remove(threading.currentThread())
subprocess not exit successfully
Error while execute command 'nmake cleanall' in direcotry C:\FishLoader\BaseTools\Source\C

Microsoft (R) Program Maintenance Utility Version 14.29.30148.0
Copyright (C) Microsoft Corporation.  All rights reserved.

C:\FishLoader\BaseTools\Source\C\Makefiles\NmakeSubdirs.py:135: DeprecationWarning: currentThread() is deprecated, use current_thread() instead
  self.running.remove(threading.currentThread())
execute command "nmake cleanall" in directory C:\FishLoader\BaseTools\Source\C\Common

Microsoft (R) Program Maintenance Utility Version 14.29.30148.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        del /f /q BasePeCoff.obj  BinderFuncs.obj  CommonLib.obj  Crc32.obj  Decompress.obj  EfiCompress.obj  EfiUtilityMsgs.obj  FirmwareVolumeBuffer.obj  FvLib.obj  MemoryFile.obj  MyAlloc.obj  OsPath.obj  ParseGuidedSectionTools.obj  ParseInf.obj  PeCoffLoaderEx.obj  SimpleFileParsing.obj  StringFuncs.obj  TianoCompress.obj C:\FishLoader\BaseTools\Lib\Win32\Common.lib *.pdb > nul
Could Not Find C:\FishLoader\BaseTools\Source\C\Common\BasePeCoff.obj
Could Not Find C:\FishLoader\BaseTools\Lib\Win32\Common.lib
Could Not Find C:\FishLoader\BaseTools\Source\C\Common\*.pdb

execute command "nmake cleanall" in directory C:\FishLoader\BaseTools\Source\C\VfrCompile

Microsoft (R) Program Maintenance Utility Version 14.29.30148.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        DEL VfrParser.dlg EfiVfrParser.cpp EfiVfrParser.h  VfrLexer.cpp VfrLexer.h  VfrSyntax.cpp VfrTokens.h
Could Not Find C:\FishLoader\BaseTools\Source\C\VfrCompile\VfrParser.dlg
        pushd . & cd Pccts & nmake -nologo cleanall & popd
        pushd . & cd antlr & "E:\Visual Studio 2022\Visual Studio IDE\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.exe" /nologo /f AntlrMS.mak cleanall & popd
        del *.obj
Could Not Find C:\FishLoader\BaseTools\Source\C\VfrCompile\Pccts\antlr\*.obj
        del *.ilk
Could Not Find C:\FishLoader\BaseTools\Source\C\VfrCompile\Pccts\antlr\*.ilk
        del *.pdb
Could Not Find C:\FishLoader\BaseTools\Source\C\VfrCompile\Pccts\antlr\*.pdb
        del *.exe
Could Not Find C:\FishLoader\BaseTools\Source\C\VfrCompile\Pccts\antlr\*.exe
        del C:\FishLoader\BaseTools\Bin\Win32\antlr.exe
Could Not Find C:\FishLoader\BaseTools\Bin\Win32\antlr.exe
        pushd . & cd dlg & "E:\Visual Studio 2022\Visual Studio IDE\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.exe" /nologo /f DlgMS.mak cleanall & popd
        del *.obj
Could Not Find C:\FishLoader\BaseTools\Source\C\VfrCompile\Pccts\dlg\*.obj
        del *.ilk
Could Not Find C:\FishLoader\BaseTools\Source\C\VfrCompile\Pccts\dlg\*.ilk
        del *.pdb
Could Not Find C:\FishLoader\BaseTools\Source\C\VfrCompile\Pccts\dlg\*.pdb
        del *.exe
Could Not Find C:\FishLoader\BaseTools\Source\C\VfrCompile\Pccts\dlg\*.exe
        del C:\FishLoader\BaseTools\Bin\Win32\dlg.exe
Could Not Find C:\FishLoader\BaseTools\Bin\Win32\dlg.exe
        del /f /q AParser.obj DLexerBase.obj ATokenBuffer.obj  EfiVfrParser.obj VfrLexer.obj VfrSyntax.obj  VfrFormPkg.obj VfrError.obj VfrUtilityLib.obj VfrCompiler.obj C:\FishLoader\BaseTools\Bin\Win32\VfrCompile.exe *.pdb C:\FishLoader\BaseTools\Bin\Win32\VfrCompile.pdb > nul
Could Not Find C:\FishLoader\BaseTools\Source\C\VfrCompile\AParser.obj
Could Not Find C:\FishLoader\BaseTools\Bin\Win32\VfrCompile.exe
Could Not Find C:\FishLoader\BaseTools\Source\C\VfrCompile\*.pdb
Could Not Find C:\FishLoader\BaseTools\Bin\Win32\VfrCompile.pdb

subprocess not exit successfully
Error while execute command 'nmake cleanall' in direcotry C:\FishLoader\BaseTools\Source\C\BrotliCompress

Microsoft (R) Program Maintenance Utility Version 14.29.30148.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        del /f /q BrotliCompress.obj  brotli\c\common\constants.obj  brotli\c\common\context.obj  brotli\c\common\dictionary.obj  brotli\c\common\platform.obj  brotli\c\common\shared_dictionary.obj  brotli\c\common\transform.obj  brotli\c\dec\bit_reader.obj  brotli\c\dec\decode.obj  brotli\c\dec\huffman.obj  brotli\c\dec\state.obj  brotli\c\enc\command.obj  brotli\c\enc\compound_dictionary.obj  brotli\c\enc\backward_references.obj  brotli\c\enc\fast_log.obj  brotli\c\enc\backward_references_hq.obj  brotli\c\enc\bit_cost.obj  brotli\c\enc\block_splitter.obj  brotli\c\enc\brotli_bit_stream.obj  brotli\c\enc\cluster.obj  brotli\c\enc\compress_fragment.obj  brotli\c\enc\compress_fragment_two_pass.obj  brotli\c\enc\dictionary_hash.obj  brotli\c\enc\encode.obj  brotli\c\enc\encoder_dict.obj  brotli\c\enc\entropy_encode.obj  brotli\c\enc\histogram.obj  brotli\c\enc\literal_cost.obj  brotli\c\enc\memory.obj  brotli\c\enc\metablock.obj  brotli\c\enc\static_dict.obj  brotli\c\enc\utf8_util.obj C:\FishLoader\BaseTools\Bin\Win32\BrotliCompress.exe *.pdb C:\FishLoader\BaseTools\Bin\Win32\BrotliCompress.pdb > nul
The system cannot find the path specified.
NMAKE : fatal error U1077: 'del' : return code '0x1'
Stop.

NMAKE : fatal error U1077: 'if' : return code '0x1'
Stop.

NMAKE : fatal error U1077: 'if' : return code '0x1'
Stop.

Microsoft (R) Program Maintenance Utility Version 14.29.30148.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Microsoft (R) Program Maintenance Utility Version 14.29.30148.0
Copyright (C) Microsoft Corporation.  All rights reserved.

######################
# Build libraries
######################

Microsoft (R) Program Maintenance Utility Version 14.29.30148.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl.exe -c  /nologo /Z7 /c /O2 /MT /W4 /WX /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /nologo /Z7 /c /O2 /MT /W4 /WX /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE  -I . -I C:\FishLoader\BaseTools\Source\C\Include -I C:\FishLoader\BaseTools\Source\C\Include\Ia32 -I C:\FishLoader\BaseTools\Source\C\Common -I . -I C:\FishLoader\BaseTools\Source\C\Include -I C:\FishLoader\BaseTools\Source\C\Include\Ia32 -I C:\FishLoader\BaseTools\Source\C\Common BasePeCoff.c -FoBasePeCoff.obj
BasePeCoff.c
BasePeCoff.c(138): error C2220: the following warning is treated as an error
BasePeCoff.c(138): warning C4311: 'type cast': pointer truncation from 'void *' to 'UINTN'
BasePeCoff.c(138): warning C4312: 'type cast': conversion from 'UINTN' to 'EFI_IMAGE_OPTIONAL_HEADER_UNION *' of greater size
BasePeCoff.c(571): warning C4312: 'type cast': conversion from 'UINTN' to 'UINT8 *' of greater size
BasePeCoff.c(639): warning C4312: 'type cast': conversion from 'UINTN' to 'EFI_IMAGE_OPTIONAL_HEADER_UNION *' of greater size
BasePeCoff.c(713): warning C4312: 'type cast': conversion from 'UINTN' to 'EFI_TE_IMAGE_HEADER *' of greater size
BasePeCoff.c(727): warning C4312: 'type cast': conversion from 'UINTN' to 'EFI_IMAGE_BASE_RELOCATION *' of greater size
BasePeCoff.c(728): warning C4311: 'type cast': pointer truncation from 'EFI_IMAGE_BASE_RELOCATION *' to 'UINTN'
BasePeCoff.c(728): warning C4312: 'type cast': conversion from 'UINTN' to 'EFI_IMAGE_BASE_RELOCATION *' of greater size
BasePeCoff.c(750): warning C4312: 'type cast': conversion from 'UINTN' to 'CHAR8 *' of greater size
BasePeCoff.c(753): warning C4312: 'type cast': conversion from 'UINTN' to 'CHAR8 *' of greater size
BasePeCoff.c(755): warning C4312: 'type cast': conversion from 'UINTN' to 'CHAR8 *' of greater size
BasePeCoff.c(792): warning C4311: 'type cast': pointer truncation from 'CHAR8 *' to 'UINTN'
BasePeCoff.c(802): warning C4311: 'type cast': pointer truncation from 'CHAR8 *' to 'UINTN'
BasePeCoff.c(967): warning C4312: 'type cast': conversion from 'UINTN' to 'void *' of greater size
BasePeCoff.c(970): warning C4312: 'type cast': conversion from 'UINTN' to 'EFI_IMAGE_OPTIONAL_HEADER_UNION *' of greater size
BasePeCoff.c(988): warning C4312: 'type cast': conversion from 'UINTN' to 'void *' of greater size
BasePeCoff.c(990): warning C4312: 'type cast': conversion from 'UINTN' to 'EFI_TE_IMAGE_HEADER *' of greater size
BasePeCoff.c(1030): warning C4311: 'type cast': pointer truncation from 'CHAR8 *' to 'UINTN'
BasePeCoff.c(1031): warning C4311: 'type cast': pointer truncation from 'CHAR8 *' to 'UINTN'
BasePeCoff.c(1090): warning C4311: 'type cast': pointer truncation from 'void *' to 'UINTN'
BasePeCoff.c(1148): warning C4312: 'type cast': conversion from 'UINTN' to 'EFI_IMAGE_DEBUG_DIRECTORY_ENTRY *' of greater size
BasePeCoff.c(1171): warning C4312: 'type cast': conversion from 'UINTN' to 'void *' of greater size
BasePeCoff.c(1286): warning C4311: 'type cast': pointer truncation from 'void *' to 'UINTN'
BasePeCoff.c(1286): warning C4312: 'type cast': conversion from 'UINTN' to 'EFI_IMAGE_NT_HEADERS32 *' of greater size
BasePeCoff.c(1307): warning C4311: 'type cast': pointer truncation from 'EFI_TE_IMAGE_HEADER *' to 'UINTN'
BasePeCoff.c(1311): warning C4312: 'type cast': conversion from 'UINTN' to 'EFI_IMAGE_DEBUG_DIRECTORY_ENTRY *' of greater size
BasePeCoff.c(1376): warning C4311: 'type cast': pointer truncation from 'void *' to 'UINTN'
BasePeCoff.c(1379): warning C4312: 'type cast': conversion from 'UINTN' to 'EFI_IMAGE_DEBUG_DIRECTORY_ENTRY *' of greater size
BasePeCoff.c(1406): warning C4311: 'type cast': pointer truncation from 'void *' to 'UINTN'
BasePeCoff.c(1410): warning C4312: 'type cast': conversion from 'UINTN' to 'void *' of greater size
BasePeCoff.c(1454): warning C4311: 'type cast': pointer truncation from 'void *' to 'UINTN'
BasePeCoff.c(1454): warning C4312: 'type cast': conversion from 'UINTN' to 'EFI_IMAGE_NT_HEADERS32 *' of greater size
BasePeCoff.c(1467): warning C4312: 'type cast': conversion from 'UINTN' to 'void *' of greater size
BasePeCoff.c(1468): warning C4311: 'type cast': pointer truncation from 'void *' to 'UINTN'
BasePeCoff.c(1471): warning C4312: 'type cast': conversion from 'UINT32' to 'void *' of greater size
BasePeCoff.c(1473): warning C4312: 'type cast': conversion from 'UINT32' to 'void *' of greater size
BasePeCoff.c(1475): warning C4312: 'type cast': conversion from 'UINTN' to 'void *' of greater size
BasePeCoff.c(1477): warning C4311: 'type cast': pointer truncation from 'void *' to 'UINTN'
BasePeCoff.c(1477): warning C4311: 'type cast': pointer truncation from 'void *' to 'UINTN'
BasePeCoff.c(1477): warning C4312: 'type cast': conversion from 'UINTN' to 'void *' of greater size
NMAKE : fatal error U1077: '"E:\Visual Studio 2022\Visual Studio IDE\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'if' : return code '0x1'
Stop.
NMAKE : fatal error U1077: 'if' : return code '0x1'
Stop.

**Comment by Javagedes** [comment]
It looks like you did not compile BaseTools before attempting to do an actual build.

**Comment by gdong1** [comment]
Close this issue since it was opened for a long time and there is no update.
