### ISSUE TITLE
How to make Arrandale GPU support more resolutions?

### ISSUE THREAD

**Issue by 1457384613gh** [tianocore/edk2#4148]
## Situations of `Arrandale GPU`
If Legacy boot, `Arrandale GPU` supports `1366x768`, the same as resolution of screen, higher than `1024x768`;
If UEFI boot, `Arrandale GPU` supports `1024x768` at max, lower than resolution of screen, with graphical interface stretched horizontally.
## Precedents with Solutions
In order to avoid graphical interface stretched horizontally, teams of `CloverBootloader` have developed `CsmVideoDxe.efi` and teams of `OpenCore` have developed `BiosVideo.efi`, used to make `Arrandale GPU` loaded in the way of being loaded by CSM or Legacy Mode ,under UEFI_Mode, so graphical interface of UEFI can use higher resolutions from CSM or Legacy Mode, such as 1366x768, the same as resolution of screen, higher than `1024x768`.
https://github.com/CloverHackyColor/CloverBootloader/tree/master/CloverEFI/BiosVideo
https://github.com/acidanthera/OpenCorePkg/tree/master/Legacy/BootPlatform/BiosVideo
### Hope
- I would like so do `UEFI Grub2` and `rEFInd`.
However, `UEFI Grub2` and `rEFInd` cannot load `CsmVideoDxe.efi` or `BiosVideo.efi`.
### Ask
- Is there a `Generic EFI Video Driver` to make all bootloader x64 to achieve that?
At least, supports to make `UEFI Grub2` and `rEFInd` use higher resolutions from CSM or Legacy Mode, such as 1366x768, the same as resolution of screen, higher than `1024x768`.
- Is there any other way to achieve that?

## Information around `Arrandale GPU`
![image](https://user-images.githubusercontent.com/69227436/213923710-120c5a02-30ea-4005-b2fe-c8e9adc7b6d7.png)

_Originally posted by @1457384613gh in https://github.com/tianocore/edk2/discussions/4140_

**Comment by lersek** [comment]
This issue may be valid/live, but you're clearly not going to get answers here. The edk2-discuss mailing list is potentially a better place. Keyword being "potentially".

**Comment by acoul** [comment]
very insightful input
