### ISSUE TITLE
Change devcontainer to Fedora 39

### ISSUE THREAD

**Issue by osteffenrh** [tianocore/edk2#5111]
Fedora 35 is EOL for some time now. The Dockerfile does not build anymore.

Switch devcontainer to the Fedora 39 image.

**Comment by osteffenrh** [comment]
Depends on https://github.com/tianocore/containers/issues/84

**Comment by lersek** [comment]
@osteffenrh https://github.com/tianocore/containers/pull/88 seems to have been merged :)

**Comment by osteffenrh** [comment]
@lersek, true.
I would like to keep devcontainer and CI image the same. Last time I tried to switch CI to Fedora 39, I had problems with gcc13 and some CI job.

Let me check that again first.

**Comment by helix-osdev** [comment]
> @lersek, true. I would like to keep devcontainer and CI image the same. Last time I tried to switch CI to Fedora 39, I had problems with gcc13 and some CI job.
> 
> Let me check that again first.

Sounds like a skill issue.

**Comment by osteffenrh** [comment]
@helix-osdev, contributions are always welcome.

**Comment by bcran** [comment]
I just saw this issue. I updated the devcontainer to Fedora 39 a few days ago - see https://github.com/tianocore/edk2/pull/5782
