### ISSUE TITLE
Bug with data unmarshaling in SecurityPkg/Library/Tpm2CommandLib/Tpm2Object.c

### ISSUE THREAD

**Issue by wmjdgla** [tianocore/edk2#5536]
`OutPublic->publicArea.parameters.rsaDetail.exponent` is 32 bits but is
unmarshaled as 16 bits:
https://github.com/tianocore/edk2/blob/b7f8779fe1f60113fdaab3b2f3f17c9f900b0456/SecurityPkg/Library/Tpm2CommandLib/Tpm2Object.c#L255-L256

Definition of the struct in which `exponent` resides:
https://github.com/tianocore/edk2/blob/b7f8779fe1f60113fdaab3b2f3f17c9f900b0456/MdePkg/Include/IndustryStandard/Tpm20.h#L1582-L1587

**Comment by jyao1** [comment]
Yes, agree this is a bug. Do you want to propose a patch?
