### ISSUE TITLE
Compilation Errors with Xcode 7/clang on OS X 10.11

### ISSUE THREAD

**Issue by theracermaster** [tianocore/edk2#73]
When compiling with EDK2 using Xcode as the toolchain, errors occur. Removing `-ftrap-function=undefined_behavior_has_been_optimized_away_by_clang` in Conf/build_rules.txt seems to fix the issue, and compilation is successful. The build_tools.template might need to be updated for Xcode 7.

**Comment by ajfish** [comment]
No -ftrap-function is functioning as intended. The C code that is failing contains C undefined behavior and without -ftrap-function the LLVM optimizer will emit a trap assembly instruction, ud2 on x86, and optimize away all the code after that point, including the ret for the function. 

Thus the -ftrap-function is a diagnostic that causes a link error on undefined behavior to make it easier to track down the code. 

See this blog post for an explanation of wha tis going on: http://blog.llvm.org/2011/05/what-every-c-programmer-should-know.html

It could be as simple as dereferencing a NULL pointer:
~/work/Compiler>cat undefined.c

int
main ()
{
  int *Yikes = 0;

  *Yikes = 1;
  return 0;
}

~/work/Compiler>clang -Os -S -ftrap-function=undefined_behavior_has_been_optimized_away_by_clang undefined.c
~/work/Compiler>cat undefined.s
	.section	__TEXT,__text,regular,pure_instructions
	.macosx_version_min 10, 11
	.globl	_main
_main:                                  ## @main
	.cfi_startproc
## BB#0:
	pushq	%rbp
Ltmp0:
	.cfi_def_cfa_offset 16
Ltmp1:
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
Ltmp2:
	.cfi_def_cfa_register %rbp
	callq	_undefined_behavior_has_been_optimized_away_by_clang
	.cfi_endproc


.subsections_via_symbols

~/work/Compiler>clang -Os -S undefined.c
~/work/Compiler>cat undefined.s
	.section	__TEXT,__text,regular,pure_instructions
	.macosx_version_min 10, 11
	.globl	_main
_main:                                  ## @main
	.cfi_startproc
## BB#0:
	pushq	%rbp
Ltmp0:
	.cfi_def_cfa_offset 16
Ltmp1:
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
Ltmp2:
	.cfi_def_cfa_register %rbp
	ud2
	.cfi_endproc


.subsections_via_symbols
