### ISSUE TITLE
tools_def.txt Enhancement

### ISSUE THREAD

**Issue by STLVNUB** [tianocore/edk2#77]
Hi. Not really an issue, but it is, IMHO

The tools_def file is growing rather large, so I propose to split it into sub TOOL_CHAIN files.
i.e 
Make all Tool chains seperate files.
e.g
VS_TOOLS.txt: Contains ALL VS data
GCC_TOOLS.txt: Contains ALL GCC data
ICC_TOOLS.txt: etc
UNIXGCC.txt: etc

Then the tools_def.txt will be quite small and the other files will be easier to manage.

Also 
Defining  a NASM and MAKE variables for custom building.
e.g  building on OS X using GCC49, nasm and make will fail.

____*_NASM_PATH                = nasm
change to
*_____NASM_PATH                = ENV(NASM_PREFIX)/nasm

__GCC49___MAKE_PATH      = DEF(GCC44_IA32_PREFIX)make
change to
*_GCC49_*_MAKE_PATH      = make

**Comment by nms42** [comment]
Some kind of 'include' (for the benefit of common code) would be good ;-)

**Comment by Download-Fritz** [comment]
Michael Zimmermann just submited a patch that allows !include in tools_def. :)
