### ISSUE TITLE
Csm16.bin(seabios) failed to work in OVMF.

### ISSUE THREAD

**Issue by wqlxx** [tianocore/edk2#82]
I build the Csm16.bin from source code of seabios-1.9.2.tar.gz . And copy the Csm16.bin to OvmfPkg/Csm/Csm16/Csm16.bin , Build the OVMF_CODE.fd and OVMF_VARS.fd with command build -D CSM_ENABLE.
   Unfortunately, I test the OVMF_CODE.fd and OVMF_VARS.fd in qemu. It failed!
The log is:
        ASSERT_EFI_ERROR (Status = Not Found)
        ASSERT /root/tianocore-edk2/IntelFrameworkModulePkg/Csm/LegacyBiosDxe/LegacyBios.c(982): !EFI_ERROR (Status)

**Comment by lersek** [comment]
Discussion on-list: http://thread.gmane.org/gmane.comp.bios.edk2.devel/11148

**Comment by lersek** [comment]
Not an OVMF bug. Please lower the size of the SeaBIOS CSM binary to e.g. 192 KB (`CONFIG_ROM_SIZE=192`). Please see the discussion linked above for details.

**Comment by lersek** [comment]
This (closed) item has been manually migrated to
https://tianocore.acgmultimedia.com/show_bug.cgi?id=84
