### ISSUE TITLE
QuarkPlatformPkg output junks on the console

### ISSUE THREAD

**Issue by mytbk** [tianocore/edk2#92]
I've built a Quark firmware for Galileo Gen2, but the console only gives junks.

**Comment by mytbk** [comment]
It can be solved if I change the default baud rate to 115200 in Quark.dsc.

**Comment by mdkinney** [comment]
The default baud rate or Gen2 is 921600.  Is the serial interface you are using between your host and Galileo compatible with 921600 baud?
What serial terminal application are you using?
